services:
  # Backend API Service
  - type: web
    name: ott-platform-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 1d
      - key: JWT_REFRESH_EXPIRE
        value: 7d
      - key: ADMIN_EMAIL
        value: 231fa04a47@gmail.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false

  # Frontend Static Site
  - type: web
    name: ott-platform-frontend
    env: static
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
